name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autoconf
      run: cd lib/parser && autoconf
    - name: configure
      run: cd lib/parser && ./configure
    - name: make
      run: cd lib/parser && make
