name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: install prerequisites
    steps:
    - uses: actions/checkout@v2
    - name: setup julia environment
      uses: julia-actions/setup-julia@1.7.0
    - name: configure and build
      run: |
        cd lib/parser 
        autoconf
        ./configure
        make
        
