name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    name: building OMParse.jl/lib/parser
    steps:
    - uses: actions/checkout@v2
    - name: setup julia environment
      uses: julia-actions/setup-julia@v1
      with:
        version: "1.7.0"
    - name: setup msys2 environment
      uses: msys2/setup-msys2@v2
      with:
        update: false
        platform-check-severity: warn
        install: base-devel mingw-w64-x86_64-toolchain
    - name: configure the library and build
      shell: msys2 {0}
      run: |
        cd lib/parser 
        autoconf
        ./configure
        make
